anglo_spanish = {
    "no quiero hacerlo": "I don't want to do it",
    "necesito hacerlo ahora": "I need to do it right now",
    "no lo tienes": "You don't have it",
    "yo no bebo": "I don't drink",
    "sabes donde esta el grande?": "Do you know where the big one is?",
    "donde estas?": "Where are you?",
    "se donde estas": "I know where you are",
    "puedo saber donde estas ahora?": "Can I know where you are now?",
    "no puedo ver donde estas": "I can't see where you are",
    "no puedo ver donde esta": "I can't see where it is",
    "puedes ver donde esta mi telefono?": "Can you see where my telephone is?",
    "donde esta tu casa?": "Where is your house?",
    "el hotel es muy pequeno": "The hotel is very small",
    "esta aqui": "It's here",
    "no esta alli": "It's not there",
    "es muy pequeno alli": "It's very small there",
    "es muy bueno aqui": "It's very good here",
    "puedo ver el grande por favor?": "Can I see the big one please?",
    "tienes el grande o el pequeno?": "Do you have the big one or the small one?",
    "no puedes hacerlo porque es muy pequeno": "You can't do it because it's very small",
    "sabes por que no lo tengo?": "Do you know why I don't have it?",
    "se que puedo hacerlo": "I know that I can do it",
    "sabes que quiero?": "Do you know what I want?",
    "sabes donde esta?": "Do you know where it is?",
    "no se donde esta tu telefono": "I don't know where your phone is",
    "no quiero verlo": "I don't want to see it",
    "no quieres ver mi computadora?": "Don't you want to see my computer?",
    "quiero verlo por favor": "I want to see it, please",
    "porque tu computadora es muy bueno": "Because your computer is very good",
    "por que quieres mi computadora?": "Why do you want my computer?",
    "necesito hacerlo porque es muy importante para mi": "I need to do it because it is very important for me",
    "lo siento pero estoy muy ocupado ahora": "I'm sorry but I'm very busy right now",
    "estoy cansado hoy": "I'm tired today",
    "no quiero hacerlo porque estoy cansado": "I don't want to do it because I'm tired",
    "necesito un cafe porque estoy cansado": "I need a coffee because I'm tired",
    "quiero saber por que no puedes hacerlo para mi hoy": "I want to know why you can't do it for me today",
    "sabes que estoy aqui para ti": "you know that I'm here for you",
    "te necesito, me necesitas": "I need you, you need me",
    "estoy aqui pero estas alli": "I am here but you are there",
    "no se donde estoy": "I don't know where I am",
    "no se por que no puedes hacerlo asi": "I don't know whey you can't do it like that",
    "quiero saber porque es importante": "I want to know because it's important",
    "por que quieres hacerlo?": "Why do you want to do it?",
    "no lo tengo porque no lo quiero y no lo necesito": "I don't have it because I don't want it and I don't need it",
    "lo quiero porque es importante": "I want it because it's important",
    "quiero saber por que no lo tienes para mi ahora": "I want to know why you don't have it for me now",
    "que es esto que es esso?": "What is this What is that?",
    "quero hacer esso": "I want to do that",
    "no puedo hacer esto hoy": "I can't do this today",
    "es esto una computador o un telefono?": "Is this a computer or a telephone?",
    "tengo que salir esta noche": "I have to leave tonight",
    "por que no quieres salir manana?": "Why don't you want to leave tomorrow?",
    "cuando tienes que salir?": "When do you have to leave?",
    "cuando quieres verlo?": "When do you want to see it?",
    "esto es muy dificil para mi": "This is very difficult for me",
    "tengo que hacerlo esta noche porque estoy ocupado": "I have to do it tonight because I'm busy",
    "tengo que salir manana": "I have to leave tomorrow",
    "esto no es una cerveza es un cafe": "This is not a beer it's a coffee",
    "por que tienes que salir ahora?": "Why do you have to leave now?",
    "donde esta tu hotel?": "Where is your hotel?",
    "puedo verlo esta noche?": "Can I see it tonight?",
    "lo siento pero estoy muy cansado hoy": "I'm sorry but I'm very tired today",
    "sabes que estoy muy ocupado?": "Do you know that I'm very busy?",
    "quieres cenar ahora?": "Do you want to have dinner now?",
    "donde quieres cenar?": "Where do you want to have dinner?",
    "donde quieres comer manana?": "Where do you want to have lunch tomorrow?",
    "no puedo cenar porque estoy muy ocupado": "I can't have dinner because I'm very busy",
    "estas seguro que es posible?": "Are you sure that it's possible?",
    "estoy seguro que la casa no esta alli": "I am sure that the house is not there",
    "quiero tenerlo hoy": "I want to have it today",
    "tengo que tenerlo ahora porque es muy importante": "I have to have it now because it's very important",
    "donde quieres cenar?": "Where do you want to have dinner?",
    "no puedo comer porque tengo que salir ahora": "I can't have lunch because I have to leave now",
    "cuando lo haces?": "When do you do it?",
    "sabes donde esta mi silla?": "do you know where my chair is?",
    "necesito la computador grande": "I need the big computer",
    "quieres salir esta noche o manana?": "Do you want to leave tonight or tomorrow?",
    "estas seguro que el hotel esta aqui?": "Are you sure that the hotel is here?",
    "perdone quiero un agua por favor": "Excuse me I want a water please",
    "puedo salir ahora?": "Can I leave now?",
    "por que sales ahora?": "Why are you leaving now?",
    "ella no tiene una computadora": "She doesn't have a computer",
    "el necesita hacerlo para ti": "He needs to do it for you",
    "donde cena?":"Where does she have dinner?",
    "sabe por que no lo tengo": "She knows why I don't have it",
    "carlos come en el coche": "Carlos has lunch in the car",
    "sabes cuando tienes que salir?": "Do you know when you have to leave?",
    "el telefono esta en la mesa?": "Is the phone on the table?",
    "no lo tengo porque no lo necesito": "I don't have it because I don't need it",
}
