anglo_spanish = {
    "no quiero hacerlo": "I don't want to do it",
    "necesito hacerlo ahora": "I need to do it right now",
    "no lo tienes": "You don't have it",
    "yo no bebo": "I don't drink",
    "sabes donde esta el grande?": "Do you know where the big one is?",
    "donde estas?": "Where are you?",
    "se donde estas": "I know where you are",
    "puedo saber donde estas ahora?": "Can I know where you are now?",
    "no puedo ver donde estas": "I can't see where you are",
    "no puedo ver donde esta": "I can't see where it is",
    "puedes ver donde esta mi telefono?": "Can you see where my telephone is?",
    "donde esta tu casa?": "Where is your house?",
    "el hotel es muy pequeno": "The hotel is very small",
    "esta aqui": "It's here",
    "no esta alli": "It's not there",
    "es muy pequeno alli": "It's very small there",
    "es muy bueno aqui": "It's very good here",
    "puedo ver el grande por favor?": "Can I see the big one please?",
    "tienes el grande o el pequeno?": "Do you have the big one or the small one?",
    "no puedes hacerlo porque es muy pequeno": "You can't do it because it's very small",
    "sabes por que no lo tengo?": "Do you know why I don't have it?",
    "se que puedo hacerlo": "I know that I can do it",
    "sabes que quiero?": "Do you know what I want?",
    "sabes donde esta?": "Do you know where it is?",
    "no se donde esta tu telefono": "I don't know where your phone is",
    "no quiero verlo": "I don't want to see it",
    "no quieres ver mi computadora?": "Don't you want to see my computer?",
    "quiero verlo por favor": "I want to see it, please",
    "porque tu computadora es muy bueno": "Because your computer is very good",
    "por que quieres mi computadora?": "Why do you want my computer?",
    "necesito hacerlo porque es muy importante para mi": "I need to do it because it is very important to me",
    "lo siento pero estoy muy ocupado ahora": "I'm sorry but I'm very busy right now",
    "estoy cansado oy": "I'm tired today",
    "no quiero hacerlo porque estoy cansado": "I don't want to do it because I'm tired",
    "necesito un cafe porque estoy cansado": "I need a coffee because I'm tired",
    "quiero saber por que no puedes hacerlo para mi oy": "I want to know why you can't do it for me today",
    "sabes que estoy aqui para ti": "you know that I'm here for you",
    "te necesito, me necesitas": "I need you, you need me",
    "estoy aqui pero estas alli": "I am here but you are there",
    "no se donde estoy": "I don't know where I am",
    "no se por que no puedes hacerlo asi": "I don't know whey you can't do it like that",
    "queiro saber proque es importante": "I want to know because it's important",
    "por que quieres hacerlo?": "Why do you want to do it?",
    "no lo tengo porque no lo quiero y no lo necesito": "I don't have it because I don't want it and I don't need it",
    "lo quiero porque es importante": "I want it because it's important",
    "quiero saber por que no lo tienes para mi ahora": "I want to know why you don't have it for me now",
}
